import { StyleSheet, Platform, StatusBar } from "react-native";
import { ThemeContextType } from "../lib/theme";

export const createHomeStyles = (colors: ThemeContextType["colors"]) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
    },
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    title: {
      fontSize: 24,
      fontWeight: "bold",
      color: colors.text,
    },
    themeButton: {
      padding: 8,
      borderRadius: 20,
      backgroundColor: colors.primary + "20",
    },
    addForm: {
      backgroundColor: colors.card,
      padding: 16,
      marginHorizontal: 16,
      borderRadius: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      marginBottom: 12,
      fontSize: 16,
      backgroundColor: colors.background,
      color: colors.text,
    },
    toggleContainer: {
      flexDirection: "row",
      marginBottom: 12,
    },
    toggleButton: {
      flex: 1,
      backgroundColor: colors.card,
      paddingVertical: 8,
      paddingHorizontal: 16,
      marginHorizontal: 4,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    toggleButtonActive: {
      backgroundColor: colors.primary,
    },
    toggleButtonText: {
      color: colors.muted,
      textAlign: "center",
      fontWeight: "600",
    },
    toggleButtonTextActive: {
      color: "#fff",
    },
    addButton: {
      backgroundColor: colors.secondary,
      paddingVertical: 12,
      borderRadius: 12,
    },
    addButtonText: {
      color: "#fff",
      textAlign: "center",
      fontSize: 16,
      fontWeight: "600",
    },
    modalContainer: {
      flex: 1,
      marginTop: 60,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
    },
    closeButton: {
      padding: 8,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: "500",
      color: colors.text,
      marginBottom: 4,
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 8,
    },
    cancelButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
    },
    saveButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: colors.primary,
    },
    buttonText: {
      color: colors.text,
      fontWeight: "600",
    },
    saveButtonText: {
      color: "#fff",
      fontWeight: "600",
    },
    filterContainer: {
      flexDirection: "row",
      paddingHorizontal: 16,
      marginBottom: 16,
      gap: 8,
    },
    filterButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    filterButtonActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    filterButtonText: {
      color: colors.muted,
      fontSize: 14,
      fontWeight: "500",
    },
    filterButtonTextActive: {
      color: "#fff",
    },
    sortButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.card,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 4,
    },
    sortModalOption: {
      paddingVertical: 16,
      paddingHorizontal: 24,
    },
    sortModalOptionText: {
      color: colors.text,
      fontSize: 16,
    },
    sortModalOptionActive: {
      backgroundColor: colors.primary + "10",
    },
    sortModalOptionTextActive: {
      color: colors.primary,
      fontWeight: "600",
    },
    modalOverlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background + "CC",
      width: "100%",
    },
    searchContainer: {
      marginHorizontal: 16,
      marginBottom: 16,
    },
    searchInput: {
      flex: 1,
      height: 40,
      backgroundColor: colors.card,
      borderRadius: 20,
      paddingHorizontal: 16,
      color: colors.text,
      fontSize: 16,
      width: "100%",
      maxWidth: "100%",
    },
    headerButtons: {
      flexDirection: "row",
      gap: 8,
    },
    iconButton: {
      padding: 8,
      borderRadius: 20,
      backgroundColor: colors.primary + "20",
    },
    emptyContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 32,
    },
    emptyText: {
      fontSize: 16,
      color: colors.muted,
      textAlign: "center",
      marginTop: 8,
    },
    emptyIcon: {
      marginBottom: 16,
      opacity: 0.5,
    },
    movieList: {
      padding: 16,
    },
    searchActiveContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    searchHeader: {
      flexDirection: "row",
      alignItems: "center",
      padding: 16,
      gap: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.card,
    },
    searchResults: {
      paddingTop: 8,
    },
    backButton: {
      padding: 4,
    },
    watchedButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.card,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 12,
      gap: 8,
    },
    watchedButtonActive: {
      backgroundColor: colors.primary + "20",
      borderColor: colors.primary,
    },
    watchedButtonText: {
      color: colors.muted,
      fontSize: 16,
      fontWeight: "500",
    },
    watchedButtonTextActive: {
      color: colors.primary,
      fontWeight: "600",
    },
    loadingContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 24,
    },
    loadingText: {
      fontSize: 16,
      color: colors.muted,
      textAlign: "center",
      marginTop: 10,
    },
    fab: {
      position: "absolute",
      bottom: 24,
      right: 24,
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: "center",
      alignItems: "center",
      elevation: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
    },
    gridContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
  }); 